version: 2
general:
  artifacts:
    - "coverage.out"
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/seike460/s3ry
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint github.com/haya14busa/goverage
      - run: golint ./...
      - run: go vet ./...
      - run: touch testUploadFile
      - run: goverage -v -coverprofile=coverage.out ./...
      - store_artifacts:
          path: coverage.out
          destination: coverage.out
      - run: go tool cover -html coverage.out -o coverage.html
      - store_artifacts:
          path: coverage.html
          destination: coverage.html
